subscriptions:
  - name: ssrsub
    url: "https://raw.githubusercontent.com/ssrsub/ssr/refs/heads/master/v2ray"
#  - name: snakem982
#    url: "https://raw.githubusercontent.com/snakem982/proxypool/refs/heads/main/source/v2ray-2.txt"

